version: '3.8'

services:
  web:
    container_name: paiss-${ENVIRONMENT}
    build: .
    networks:
      - platform
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  platform:
    external: true
