version: '3.8'

# =============================================================================
# PAISS - Company Website Deployment
# =============================================================================

networks:
  platform:
    external: true
    name: platform

services:
  # ===========================================================================
  # PAISS Web (Static Site)
  # ===========================================================================
  paiss-web:
    image: ${IMAGE:-ghcr.io/duersjefen/paiss:latest}
    container_name: ${CONTAINER_NAME:-paiss-web}
    restart: unless-stopped
    networks:
      - platform
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "project=paiss"
      - "environment=production"
